### ISSUE TITLE
SU Request Fails on AOSP OpenMaster

### ISSUE THREAD

**Issue by laurelmay** [koush/Superuser#161] opened 2013-07-02 05:26 UTC
On AOSP OpenMaster (Android 4.2.2.2.2.2.2.2.2.2), SuperUser requests are always denied and no prompt is displayed. I have attempted a superuser request with the default settings in the Superuser app and after modifying them (Allow requests from all users; allow requests by default).
A dialog never appears to Deny/Allow the request, just automatic denial when any app attempts a superuser request, however shell requests succeed without an issue.

The following is a snippet from a logcat on grouper using ROM Manager to flash a recovery on AOSP OpenMaster. 

`W/su      ( 8090): request rejected (10076->0 . /data/data/com.koushikdutta.rommanager/files/rommanager.sh) 
D/su      ( 8087): su invoked. 
E/su      ( 8088): chown (/dev/com.koushikdutta.superuser, 10032, 10032) failed with 1: Operation not permitted`

**Comment by koush** [comment] 2013-07-02 05:35
Make sure su is setuid?

**Comment by laurelmay** [comment] 2013-07-03 04:13
Permissions are set at 6755, setuid and setgid. Still no go. 

`# ls -l su
-rwsr-sr-x root     root       366952 2013-07-02 00:41 su`

According to some people I've talked to since posting this issue, it could be an issue with AOSP's libc rather than Superuser. I'm not going to pretend I know any details more than that. I've just been told it's a libc issue. Thought it'd be worth mentioning here.

**Comment by jk2K** [comment] 2013-07-03 04:20
superuser is broken in android  4.2, use android 4.1 please

**Comment by koush** [comment] 2013-07-03 06:46
@kalaker Check if you can create /dev/com.koushikdutta.superuser while root

adb root
adb shell
mkdir /dev/com.koushikdutta.superuser

**Comment by laurelmay** [comment] 2013-07-03 13:27
Nope. It exists already. It's empty, but it exists.

`# mkdir /dev/com.koushikdutta.superuser
mkdir failed for /dev/com.koushikdutta.superuser, File exists`

**Comment by koush** [comment] 2013-07-03 15:21
And if you chown it, that works or fails?

**Comment by laurelmay** [comment] 2013-07-03 15:30
Just executing chown works with no problem.
Is there something specific it should be chowned to? It was root:root, and just to test I set it to root:system.
(I assume we're still talking about /dev/com.koushikdutta.superuser)

**Comment by simonsickle-old** [comment] 2013-07-03 16:10
@koush   if you are interested the problem is net bsd code in open master. Iirc it is the modes not being supported now

**Comment by koush** [comment] 2013-07-03 16:38
@SimonSickle what in particular is the problem?

The error seems to be on the chown request, and I don't understand why.

**Comment by koush** [comment] 2013-07-03 16:40
TBH, I can't really support every third party ROM (OpenMaster in this case) that has issues.

I'll support Google AOSP (stable), NDK builds, and CM, but beyond that, there could be an innumerable number of things wrong with the platform itself. In this case, I am guessing something terrible is wrong with libc/bionic in OpenMaster to fail in such a way (libc chown call). I'm closing this as an issue with OpenMaster, and not Superuser.

**Closed as completed by koush** 2013-07-03 16:40 UTC

**Comment by laurelmay** [comment] 2013-07-03 16:44
OpenMaster is the master branch of Google AOSP.

**Comment by koush** [comment] 2013-07-03 16:44
@kalaker I realize this, but it's also an unstable branch. It's pretty insane to be building off master :)

**Comment by simonsickle-old** [comment] 2013-07-03 22:31
@koush so after further research the problem is superuser the new chainfire binary works with open master. This appears to be something going into 4.3 release

**Comment by koush** [comment] 2013-07-04 00:13
@SimonSickle Once 4.3 code drops, I'll fix any issues, if there are any.
